[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_contract = "EXEhifUx6GviNLFiFL6TDgU49XPYqdK1gZJ5qDXvr98"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/vandycklai/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
